/// The policy-carrying table: 'Change Detector' is referenced by the refresh
/// policy alone, so the policy must keep it alive.
table Sales
	lineageTag: 11111111-1111-1111-1111-111111111111

	/// Live only through the policy's change detection.
	measure 'Change Detector' = COUNTROWS('Sales')
		lineageTag: 22222222-2222-2222-2222-222222222222

	column Amount
		dataType: double
		summarizeBy: sum
		sourceColumn: Amount
		lineageTag: 55555555-5555-5555-5555-555555555555

	column Modified
		dataType: dateTime
		summarizeBy: none
		sourceColumn: Modified
		lineageTag: 66666666-6666-6666-6666-666666666666

	/// The Desktop "Full DataView" partition: unfiltered — only the policy's
	/// sourceExpression below carries the RangeStart/RangeEnd filter.
	partition Sales = m
		mode: import
		source =
				let
				    Source = Sql.Database("server", "db"),
				    Sales_Data = Source{[Item="Sales",Kind="Table"]}[Data]
				in
				    Sales_Data

	refreshPolicy
		policyType: basicRefreshPolicy
		incrementalGranularity: month
		incrementalPeriods: 1
		rollingWindowGranularity: year
		rollingWindowPeriods: 10
		sourceExpression =
				let
				    Source = Sql.Database("server", "db"),
				    Sales_Data = Source{[Item="Sales",Kind="Table"]}[Data],
				    Filtered = Table.SelectRows(Sales_Data, each [Modified] >= RangeStart and [Modified] < RangeEnd)
				in
				    Filtered
		pollingExpression = EVALUATE ROW("Bookmark", 'Sales'[Change Detector])
